
# travis config

language: r
sudo: false
cache: packages
#dist: trusty

addons:
  apt:
    packages:
      - libxml2-dev

r:
 - release
 - oldrel
 - devel

r_packages:
  - devtools
  - roxygen2
  - testthat
  - covr
  - rmarkdown


before_install:
  - R -e "devtools::install_deps('./pkg')"
  - R -e "devtools::document('./pkg')"
  - cd ./pkg



after_success:
  - Rscript -e 'library(covr);coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change


