
# travis config

language: r
sudo: required

addons:
  apt:
    packages:
      - libxml2-dev

r:
 - release
 - oldrel
 - devel


before_install:
  - R -e "install.packages(c('devtools','roxygen2','testthat','rmarkdown','covr'))"
  - R -e "devtools::install_deps('./pkg')"
  - R -e "devtools::document('./pkg')"
  - cd ./pkg



after_success:
  - Rscript -e 'library(covr);coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change


